### PR TITLE
include missing AnyEvent::Fork module

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by tomgross** [comment]
Anything I could do to help to get this PR merged?

**Comment by leedo** [comment]
This is no longer required

**Comment by tomgross** [comment]
This PR also adds a new provider.

**Comment by leedo** [comment]
Whoops, missed that. Cherry-picked that commit, so it should be added now.

**Comment by tomgross** [comment]
Thanks!
Lee Aylward <notifications@github.com> schrieb am So., 22. Mai 2016 um
19:16:

**Pull request closed without merging**
